//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceCaptcha
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCaptcha.CaptchaServicioWebSoap")]
    public interface CaptchaServicioWebSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceCaptcha.ValidarCaptchaResponse> ValidarCaptchaAsync(ServiceReferenceCaptcha.ValidarCaptchaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCaptchaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCaptcha", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceCaptcha.ValidarCaptchaRequestBody Body;
        
        public ValidarCaptchaRequest()
        {
        }
        
        public ValidarCaptchaRequest(ServiceReferenceCaptcha.ValidarCaptchaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCaptchaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string claveSecreta;
                
        public ValidarCaptchaRequestBody()
        {
        }
        
        public ValidarCaptchaRequestBody(string token, string claveSecreta)
        {
            this.token = token;
            this.claveSecreta = claveSecreta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCaptchaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCaptchaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceCaptcha.ValidarCaptchaResponseBody Body;
        
        public ValidarCaptchaResponse()
        {
        }
        
        public ValidarCaptchaResponse(ServiceReferenceCaptcha.ValidarCaptchaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCaptchaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidarCaptchaResult;
        
        public ValidarCaptchaResponseBody()
        {
        }
        
        public ValidarCaptchaResponseBody(bool ValidarCaptchaResult)
        {
            this.ValidarCaptchaResult = ValidarCaptchaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CaptchaServicioWebSoapChannel : ServiceReferenceCaptcha.CaptchaServicioWebSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CaptchaServicioWebSoapClient : System.ServiceModel.ClientBase<ServiceReferenceCaptcha.CaptchaServicioWebSoap>, ServiceReferenceCaptcha.CaptchaServicioWebSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CaptchaServicioWebSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CaptchaServicioWebSoapClient.GetBindingForEndpoint(endpointConfiguration), CaptchaServicioWebSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaptchaServicioWebSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CaptchaServicioWebSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaptchaServicioWebSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CaptchaServicioWebSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CaptchaServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceCaptcha.ValidarCaptchaResponse> ServiceReferenceCaptcha.CaptchaServicioWebSoap.ValidarCaptchaAsync(ServiceReferenceCaptcha.ValidarCaptchaRequest request)
        {
            return base.Channel.ValidarCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceCaptcha.ValidarCaptchaResponse> ValidarCaptchaAsync(string token, string claveSecreta)
        {
            ServiceReferenceCaptcha.ValidarCaptchaRequest inValue = new ServiceReferenceCaptcha.ValidarCaptchaRequest();
            inValue.Body = new ServiceReferenceCaptcha.ValidarCaptchaRequestBody();
            inValue.Body.token = token;
            inValue.Body.claveSecreta = claveSecreta;
            return ((ServiceReferenceCaptcha.CaptchaServicioWebSoap)(this)).ValidarCaptchaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CaptchaServicioWebSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CaptchaServicioWebSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CaptchaServicioWebSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58505/CaptchaServicioWeb.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CaptchaServicioWebSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58505/CaptchaServicioWeb.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CaptchaServicioWebSoap,
            
            CaptchaServicioWebSoap12,
        }
    }
}
